/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.meynier.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A book author */
@org.apache.avro.specific.AvroGenerated
public class AvroAuthor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8030107468057913589L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAuthor\",\"namespace\":\"com.meynier.kafka.avro.model\",\"doc\":\"A book author\",\"fields\":[{\"name\":\"first_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"family_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"birth_date\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroAuthor> ENCODER =
      new BinaryMessageEncoder<AvroAuthor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroAuthor> DECODER =
      new BinaryMessageDecoder<AvroAuthor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroAuthor> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroAuthor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroAuthor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroAuthor>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroAuthor to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroAuthor from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroAuthor instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroAuthor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String first_name;
  @Deprecated public java.lang.String family_name;
  @Deprecated public int birth_date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroAuthor() {}

  /**
   * All-args constructor.
   * @param first_name The new value for first_name
   * @param family_name The new value for family_name
   * @param birth_date The new value for birth_date
   */
  public AvroAuthor(java.lang.String first_name, java.lang.String family_name, java.lang.Integer birth_date) {
    this.first_name = first_name;
    this.family_name = family_name;
    this.birth_date = birth_date;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first_name;
    case 1: return family_name;
    case 2: return birth_date;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first_name = (java.lang.String)value$; break;
    case 1: family_name = (java.lang.String)value$; break;
    case 2: birth_date = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return The value of the 'first_name' field.
   */
  public java.lang.String getFirstName() {
    return first_name;
  }


  /**
   * Sets the value of the 'first_name' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.String value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'family_name' field.
   * @return The value of the 'family_name' field.
   */
  public java.lang.String getFamilyName() {
    return family_name;
  }


  /**
   * Sets the value of the 'family_name' field.
   * @param value the value to set.
   */
  public void setFamilyName(java.lang.String value) {
    this.family_name = value;
  }

  /**
   * Gets the value of the 'birth_date' field.
   * @return The value of the 'birth_date' field.
   */
  public int getBirthDate() {
    return birth_date;
  }


  /**
   * Sets the value of the 'birth_date' field.
   * @param value the value to set.
   */
  public void setBirthDate(int value) {
    this.birth_date = value;
  }

  /**
   * Creates a new AvroAuthor RecordBuilder.
   * @return A new AvroAuthor RecordBuilder
   */
  public static com.meynier.kafka.avro.model.AvroAuthor.Builder newBuilder() {
    return new com.meynier.kafka.avro.model.AvroAuthor.Builder();
  }

  /**
   * Creates a new AvroAuthor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroAuthor RecordBuilder
   */
  public static com.meynier.kafka.avro.model.AvroAuthor.Builder newBuilder(com.meynier.kafka.avro.model.AvroAuthor.Builder other) {
    if (other == null) {
      return new com.meynier.kafka.avro.model.AvroAuthor.Builder();
    } else {
      return new com.meynier.kafka.avro.model.AvroAuthor.Builder(other);
    }
  }

  /**
   * Creates a new AvroAuthor RecordBuilder by copying an existing AvroAuthor instance.
   * @param other The existing instance to copy.
   * @return A new AvroAuthor RecordBuilder
   */
  public static com.meynier.kafka.avro.model.AvroAuthor.Builder newBuilder(com.meynier.kafka.avro.model.AvroAuthor other) {
    if (other == null) {
      return new com.meynier.kafka.avro.model.AvroAuthor.Builder();
    } else {
      return new com.meynier.kafka.avro.model.AvroAuthor.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroAuthor instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAuthor>
    implements org.apache.avro.data.RecordBuilder<AvroAuthor> {

    private java.lang.String first_name;
    private java.lang.String family_name;
    private int birth_date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.meynier.kafka.avro.model.AvroAuthor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.family_name)) {
        this.family_name = data().deepCopy(fields()[1].schema(), other.family_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.birth_date)) {
        this.birth_date = data().deepCopy(fields()[2].schema(), other.birth_date);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroAuthor instance
     * @param other The existing instance to copy.
     */
    private Builder(com.meynier.kafka.avro.model.AvroAuthor other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.family_name)) {
        this.family_name = data().deepCopy(fields()[1].schema(), other.family_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.birth_date)) {
        this.birth_date = data().deepCopy(fields()[2].schema(), other.birth_date);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'first_name' field.
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return first_name;
    }


    /**
      * Sets the value of the 'first_name' field.
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder setFirstName(java.lang.String value) {
      validate(fields()[0], value);
      this.first_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first_name' field.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'family_name' field.
      * @return The value.
      */
    public java.lang.String getFamilyName() {
      return family_name;
    }


    /**
      * Sets the value of the 'family_name' field.
      * @param value The value of 'family_name'.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder setFamilyName(java.lang.String value) {
      validate(fields()[1], value);
      this.family_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'family_name' field has been set.
      * @return True if the 'family_name' field has been set, false otherwise.
      */
    public boolean hasFamilyName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'family_name' field.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder clearFamilyName() {
      family_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'birth_date' field.
      * @return The value.
      */
    public int getBirthDate() {
      return birth_date;
    }


    /**
      * Sets the value of the 'birth_date' field.
      * @param value The value of 'birth_date'.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder setBirthDate(int value) {
      validate(fields()[2], value);
      this.birth_date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'birth_date' field has been set.
      * @return True if the 'birth_date' field has been set, false otherwise.
      */
    public boolean hasBirthDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'birth_date' field.
      * @return This builder.
      */
    public com.meynier.kafka.avro.model.AvroAuthor.Builder clearBirthDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroAuthor build() {
      try {
        AvroAuthor record = new AvroAuthor();
        record.first_name = fieldSetFlags()[0] ? this.first_name : (java.lang.String) defaultValue(fields()[0]);
        record.family_name = fieldSetFlags()[1] ? this.family_name : (java.lang.String) defaultValue(fields()[1]);
        record.birth_date = fieldSetFlags()[2] ? this.birth_date : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroAuthor>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroAuthor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroAuthor>
    READER$ = (org.apache.avro.io.DatumReader<AvroAuthor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.first_name);

    out.writeString(this.family_name);

    out.writeInt(this.birth_date);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.first_name = in.readString();

      this.family_name = in.readString();

      this.birth_date = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.first_name = in.readString();
          break;

        case 1:
          this.family_name = in.readString();
          break;

        case 2:
          this.birth_date = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










